// Mock provider with realistic Boston fixtures for development/backtesting
// Used when no credentials are available

export const mockProvider = {
  name: 'mock',
  requiresCredentials: false,
  rateLimit: { requests: Infinity, window: '1h' },

  async getProperty(address) {
    const fixtures = getFixtures();
    const match = fixtures.properties.find(p => 
      p.address.toLowerCase().includes(address.toLowerCase().split(',')[0].trim().toLowerCase())
    );
    return match ? { ...normalizeForInternal(match) } : null;
  },

  async getComps(address, { radius = 1, limit = 20, daysOld = 180 } = {}) {
    const fixtures = getFixtures();
    const subject = await this.getProperty(address);
    if (!subject) return [];

    // Filter comps by property type and rough geography
    const cutoffDate = new Date();
    cutoffDate.setDate(cutoffDate.getDate() - daysOld);

    const comps = fixtures.comps
      .filter(c => c.propertyType === subject.propertyType)
      .filter(c => new Date(c.saleDate) >= cutoffDate)
      .slice(0, limit)
      .map(normalizeForInternal);

    return comps;
  },

  async searchSold({ city = 'Boston', state = 'MA', limit = 50 } = {}) {
      const fixtures = getFixtures();
      return fixtures.comps
        .filter(c => c.city.toLowerCase() === city.toLowerCase() && c.state === state)
        .slice(0, limit)
        .map(normalizeForInternal);
    },

    async getMarketData(polygonId) {
      const fixtures = getFixtures();
      // Return mock market data for the given polygon
      return {
        activeListings: [],
        recentSolds: fixtures.comps.filter(c => c.city.toLowerCase() === 'boston'),
        microMarketStats: {
          [polygonId]: {
            medianPrice: 850000,
            monthsOfInventory: 2.5,
            domTrend: -0.05,
            listToSaleRatio: 0.98,
            ppsf: 480,
            grm: 12.5,
            capRate: 0.055,
            landValue: 300000,
            replacementCostPerSqft: 180,
            rentPerSqft: 3.50,
          }
        },
        neighborhoodPolys: {},
        hpiIndex: [
          { date: '2024-01', value: 320.5 },
          { date: '2024-02', value: 322.1 },
          { date: '2024-03', value: 324.0 },
          { date: '2024-04', value: 325.5 },
          { date: '2024-05', value: 327.0 },
        ],
        medianHistory: [
          { date: '2024-01', polygonId, medianPrice: 825000 },
          { date: '2024-02', polygonId, medianPrice: 835000 },
          { date: '2024-03', polygonId, medianPrice: 845000 },
          { date: '2024-04', polygonId, medianPrice: 850000 },
          { date: '2024-05', polygonId, medianPrice: 855000 },
        ],
        ppsfiByPolygon: { [polygonId]: 480 },
        grmByPolygon: { [polygonId]: 12.5 },
        capRateByPolygon: { [polygonId]: 0.055 },
        landValues: { [polygonId]: 300000 },
        replacementCostPerSqft: { single_family: 180, condo: 200, multi_family: 170 },
        totalEconomicLife: { single_family: 60, condo: 50, multi_family: 55 },
        rentPerSqftByPolygon: { [polygonId]: 3.50 },
        rentPerSqft: 3.50,
        listToSaleRatio: { [polygonId]: 0.98, default: 0.97 },
        absorptionRate: 2.5,
        monthsOfInventory: 2.5,
        domTrend: -0.05,
        zestimate: 845000,
        redfinEstimate: 855000,
        hedonicCoefficients: {
          intercept: 200000,
          sqft: 350,
          beds: 15000,
          baths: 20000,
          age: -800,
          condition: 25000,
          lotSqft: 20,
          garage: 10000,
          hoaFee: -50,
          isCondo: -50000,
          isMulti: 30000,
        },
        hedonicResiduals: [10000, -5000, 15000, -8000, 12000, -3000, 7000, -11000, 9000, -6000],
        hedonicSampleSize: 1500,
        hedonicRSquared: 0.87,
        subjectPriorSale: null,
        dataAgeMonths: 0,
      };
    }
  };

function normalizeForInternal(raw) {
  return {
    id: raw.id,
    address: raw.address,
    addressLine1: raw.addressLine1,
    city: raw.city,
    state: raw.state,
    zipCode: raw.zipCode,
    lat: raw.lat,
    lon: raw.lon,
    salePrice: raw.salePrice,
    saleDate: raw.saleDate,
    sqft: raw.sqft,
    beds: raw.beds,
    baths: raw.baths,
    propertyType: raw.propertyType,
    yearBuilt: raw.yearBuilt,
    lotSize: raw.lotSize,
    daysOnMarket: raw.daysOnMarket,
    hoaFee: raw.hoaFee,
    source: 'mock',
    raw,
  };
}

function getFixtures() {
  return {
    properties: [
      {
        id: 'subj_1',
        address: '123 Main St, Boston, MA 02129',
        addressLine1: '123 Main St',
        city: 'Boston',
        state: 'MA',
        zipCode: '02129',
        lat: 42.3768,
        lon: -71.0623,
        sqft: 1800,
        beds: 3,
        baths: 2,
        propertyType: 'single_family',
        yearBuilt: 1920,
        lotSize: 3500,
        hoaFee: 0,
      },
      {
        id: 'subj_2',
        address: '45 Beacon St, Boston, MA 02108',
        addressLine1: '45 Beacon St',
        city: 'Boston',
        state: 'MA',
        zipCode: '02108',
        lat: 42.3584,
        lon: -71.0636,
        sqft: 2200,
        beds: 3,
        baths: 2.5,
        propertyType: 'condo',
        yearBuilt: 1890,
        lotSize: 0,
        hoaFee: 650,
      },
      {
        id: 'subj_3',
        address: '78 Dorchester Ave, Boston, MA 02127',
        addressLine1: '78 Dorchester Ave',
        city: 'Boston',
        state: 'MA',
        zipCode: '02127',
        lat: 42.3382,
        lon: -71.0431,
        sqft: 3200,
        beds: 4,
        baths: 2,
        propertyType: 'multi_family',
        yearBuilt: 1900,
        lotSize: 4500,
        hoaFee: 0,
      },
    ],
    comps: [
      {
        id: 'comp_1',
        address: '115 Main St, Boston, MA 02129',
        addressLine1: '115 Main St',
        city: 'Boston',
        state: 'MA',
        zipCode: '02129',
        lat: 42.3765,
        lon: -71.0620,
        salePrice: 925000,
        saleDate: '2025-05-15',
        sqft: 1750,
        beds: 3,
        baths: 2,
        propertyType: 'single_family',
        yearBuilt: 1915,
        lotSize: 3200,
        daysOnMarket: 18,
        hoaFee: 0,
      },
      {
        id: 'comp_2',
        address: '130 Main St, Boston, MA 02129',
        addressLine1: '130 Main St',
        city: 'Boston',
        state: 'MA',
        zipCode: '02129',
        lat: 42.3772,
        lon: -71.0625,
        salePrice: 890000,
        saleDate: '2025-04-22',
        sqft: 1680,
        beds: 3,
        baths: 1.5,
        propertyType: 'single_family',
        yearBuilt: 1925,
        lotSize: 3000,
        daysOnMarket: 32,
        hoaFee: 0,
      },
      {
        id: 'comp_3',
        address: '105 Main St, Boston, MA 02129',
        addressLine1: '105 Main St',
        city: 'Boston',
        state: 'MA',
        zipCode: '02129',
        lat: 42.3760,
        lon: -71.0615,
        salePrice: 975000,
        saleDate: '2025-06-10',
        sqft: 1920,
        beds: 3,
        baths: 2.5,
        propertyType: 'single_family',
        yearBuilt: 1910,
        lotSize: 3800,
        daysOnMarket: 12,
        hoaFee: 0,
      },
      {
        id: 'comp_4',
        address: '98 Main St, Boston, MA 02129',
        addressLine1: '98 Main St',
        city: 'Boston',
        state: 'MA',
        zipCode: '02129',
        lat: 42.3758,
        lon: -71.0610,
        salePrice: 850000,
        saleDate: '2025-03-30',
        sqft: 1600,
        beds: 3,
        baths: 1,
        propertyType: 'single_family',
        yearBuilt: 1930,
        lotSize: 2800,
        daysOnMarket: 45,
        hoaFee: 0,
      },
      {
        id: 'comp_5',
        address: '142 Main St, Boston, MA 02129',
        addressLine1: '142 Main St',
        city: 'Boston',
        state: 'MA',
        zipCode: '02129',
        lat: 42.3775,
        lon: -71.0630,
        salePrice: 940000,
        saleDate: '2025-05-28',
        sqft: 1850,
        beds: 4,
        baths: 2,
        propertyType: 'single_family',
        yearBuilt: 1905,
        lotSize: 4000,
        daysOnMarket: 21,
        hoaFee: 0,
      },
      // Condo comps (Beacon Hill)
      {
        id: 'comp_6',
        address: '40 Beacon St, Boston, MA 02108',
        addressLine1: '40 Beacon St',
        city: 'Boston',
        state: 'MA',
        zipCode: '02108',
        lat: 42.3580,
        lon: -71.0630,
        salePrice: 1250000,
        saleDate: '2025-05-20',
        sqft: 2100,
        beds: 3,
        baths: 2,
        propertyType: 'condo',
        yearBuilt: 1885,
        lotSize: 0,
        daysOnMarket: 28,
        hoaFee: 720,
      },
      {
        id: 'comp_7',
        address: '50 Beacon St, Boston, MA 02108',
        addressLine1: '50 Beacon St',
        city: 'Boston',
        state: 'MA',
        zipCode: '02108',
        lat: 42.3588,
        lon: -71.0640,
        salePrice: 1180000,
        saleDate: '2025-04-15',
        sqft: 2050,
        beds: 2,
        baths: 2,
        propertyType: 'condo',
        yearBuilt: 1895,
        lotSize: 0,
        daysOnMarket: 35,
        hoaFee: 680,
      },
      {
        id: 'comp_8',
        address: '35 Beacon St, Boston, MA 02108',
        addressLine1: '35 Beacon St',
        city: 'Boston',
        state: 'MA',
        zipCode: '02108',
        lat: 42.3578,
        lon: -71.0628,
        salePrice: 1320000,
        saleDate: '2025-06-05',
        sqft: 2300,
        beds: 3,
        baths: 2.5,
        propertyType: 'condo',
        yearBuilt: 1890,
        lotSize: 0,
        daysOnMarket: 22,
        hoaFee: 750,
      },
      // Multi-family comps (South Boston)
      {
        id: 'comp_9',
        address: '72 Dorchester Ave, Boston, MA 02127',
        addressLine1: '72 Dorchester Ave',
        city: 'Boston',
        state: 'MA',
        zipCode: '02127',
        lat: 42.3378,
        lon: -71.0425,
        salePrice: 1150000,
        saleDate: '2025-05-01',
        sqft: 3100,
        beds: 4,
        baths: 2,
        propertyType: 'multi_family',
        yearBuilt: 1905,
        lotSize: 4200,
        daysOnMarket: 25,
        hoaFee: 0,
      },
      {
        id: 'comp_10',
        address: '85 Dorchester Ave, Boston, MA 02127',
        addressLine1: '85 Dorchester Ave',
        city: 'Boston',
        state: 'MA',
        zipCode: '02127',
        lat: 42.3388,
        lon: -71.0438,
        salePrice: 1080000,
        saleDate: '2025-04-10',
        sqft: 2950,
        beds: 3,
        baths: 2,
        propertyType: 'multi_family',
        yearBuilt: 1910,
        lotSize: 4000,
        daysOnMarket: 38,
        hoaFee: 0,
      },
    ],
  };
}